services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: visits
    ports:
      - "3306:3306"
    volumes:
      - node-volume:/var/lib/mysql
    # networks: 
    #   - node-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$password"]
      interval: 10s
      timeout: 5s
      retries: 5
  nodeapp:
    # find dockerfile in the same folder
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    # environment:
    #   MYSQL_HOST: db
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: password
    #   MYSQL_DATABASE: visits

volumes:
  node-volume:
